# Generated by Django 4.2.11 on 2024-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.BooleanField(),
        ),
    ]
