# Generated by Django 4.2.11 on 2024-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='494857cdb73248fbb0aea8de8a671f34', max_length=32),
        ),
    ]
