# Generated by Django 4.2.11 on 2024-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='2d64383a24044441ab1b435f69e0f044', max_length=32),
        ),
    ]
