# Generated by Django 4.2.11 on 2024-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='photo', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='b6079a89c21f40949a5beecd32dccf4e', max_length=32),
        ),
    ]
