# Generated by Django 4.2.11 on 2024-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_project_image_alter_user_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, default='photo', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, default='photo', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='7a3c2e865a47419b90296801730f9a48', max_length=32),
        ),
    ]
