# Generated by Django 4.2.11 on 2024-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_avatar_image_alter_user_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='1d29d7a7991c4bbd9ec6a0e9b32ca674', max_length=32),
        ),
    ]
