# Generated by Django 4.2.11 on 2024-06-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_url_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='654b248f7c0a4a9ea7ed50a6572ae9ea', max_length=32),
        ),
    ]
