# Generated by Django 4.2.11 on 2024-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_avatar_image_alter_user_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('api', 'api'), ('web', 'web'), ('android', 'android')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_address',
            field=models.CharField(default='071fb79ad789471ab834c8afdd584d3d', max_length=32),
        ),
    ]
