# Generated by Django 4.2.11 on 2024-05-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.about')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('gpa', models.FloatField()),
                ('grade', models.CharField(default=None, max_length=30)),
                ('image', models.BinaryField(default=None)),
                ('description', models.TextField()),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.portfolio')),
            ],
        ),
    ]
