# Generated by Django 4.2.11 on 2024-05-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_portfolio_resume_remove_about_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
            preserve_default=False,
        ),
    ]
