# Generated by Django 4.2.11 on 2024-05-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_about_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user_id',
        ),
    ]
