# Generated by Django 4.2.11 on 2024-05-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_about_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='resume_id',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='resume_id',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='about_id',
            new_name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
            preserve_default=False,
        ),
    ]
