# Generated by Django 4.2.11 on 2024-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_portfolio_id_category_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_address',
            field=models.URLField(blank=True),
        ),
    ]
